sisa/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using sisa.Models;
using sisa.DAO;
using System.Data.Entity;

namespace sisa.Controllers
{
    public class ContratoController : Controller
    {
        private SisaEntities db = new SisaEntities();
        public ActionResult ListaContratos(int codcli, string banco)
        {
            var lista = new sisa.DAO.Contrato().RetornaContratos(codcli,banco);
            return View("Lista",lista);
        }

        public PartialViewResult ListaBancos(int codcli)
        {
            var lista = new sisa.DAO.Contrato().RetornaBancos(codcli);
            return PartialView("_Bancos", lista);
        }
        public PartialViewResult ListaParcelas(string codcontrato)
        {
            var lista = new sisa.DAO.Contrato().ListaParcelas(codcontrato);
            return PartialView("Parcelas", lista);
        }

        // GET: Contrato
        public ActionResult Index()
        {
            return View();
        }

        // GET: Contrato/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        void CarregaListas()
        {
            ViewBag.ListaTipoContrato = new Dados().RetornaSelectList("SELECT TIPOCONTRATO FROM VW_TIPOCONTRATO");
            ViewBag.ListaInformativo = new Dados().RetornaSelectList("SELECT INFORMATIVO FROM VW_INFORMATIVO");
            ViewBag.ListaFaixa = new Dados().RetornaSelectList("SELECT FAIXA FROM VW_FAIXA");
            ViewBag.ListaExcluido = new Dados().ListaSelecione();
        }

        // GET: Contrato/Create
        public ActionResult Create(int codcli, string banco)
        {
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;
            ViewBag.CodBanco = new Contrato().RetornaIdBanco(banco);
            CarregaListas();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TB_CONTRATO tbContrato)
        {
            try
            {
                //if (tbContrato.VL_TOT_CONTRATO != null)
                //{
                //    tbContrato.VL_TOT_CONTRATO = Convert.ToDecimal(tbContrato.VL_TOT_CONTRATO.ToString().Replace(".", ""));
                //}

                //if (ModelState.IsValid)
                //{
                    db.TB_CONTRATO.Add(tbContrato);
                    db.SaveChanges();
                    TempData["Msg"] = "Gravado com sucesso.";
                    string dsBanco = new Contrato().RetornaNomeBanco(tbContrato.ID_BANCO);
                    return RedirectToRoute("PessoaContratos", new {codcli=tbContrato.CD_CLIENTE, banco = dsBanco });
                //}
                //else
                //{
                    TempData["MsgErro"] = "Erro: Verificar dados, tente novamente";
                //}
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro: Verificar dados, tente novamente," + ex.Message;
            }
            
            CarregaListas();
            ViewBag.CodCliente = tbContrato.CD_CLIENTE;
            ViewBag.Banco = new Contrato().RetornaNomeBanco(tbContrato.ID_BANCO);
            ViewBag.CodBanco = tbContrato.ID_BANCO;
            return View(tbContrato);

        }

        // POST: Contrato/Create
        [HttpPost]
        public ActionResult CreateOriginal(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Contrato/Edit/5
        public ActionResult Edit(string contrato)
        {   try
            {
            CarregaListas();
            var ct = new Contrato(contrato);
            ViewBag.CodCliente = ct.CodCliente;
            ViewBag.CodBanco = ct.IdBanco;
            ViewBag.Banco = ct.NomeBanco;
            
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro: Verificar dados, tente novamente," + ex.Message;
            }
            
            return View(db.TB_CONTRATO.SingleOrDefault(c=>c.CD_CONTRATO.Equals(contrato)));
        }

        // POST: Contrato/Edit/5
        [HttpPost]
        public ActionResult Edit(TB_CONTRATO tbl)
        {
            try
            {
                //if (ModelState.IsValid)
                //{
                    CarregaListas();
                    ViewBag.CodCliente = tbl.CD_CLIENTE;
                    ViewBag.Banco = new Contrato().RetornaNomeBanco(tbl.ID_BANCO);
                    ViewBag.CodBanco = tbl.ID_BANCO;

                    db.Entry(tbl).State = EntityState.Modified;
                    db.SaveChanges();

                    TempData["Msg"] = "Gravado com sucesso.";
                    string dsBanco = new Contrato().RetornaNomeBanco(tbl.ID_BANCO);
                    new Historico().Alteracao(tbl.CD_CLIENTE, tbl.ID_BANCO, "Contrato " + tbl.CD_CONTRATO + " alterado pelo usuário " + Session["CodUsuario"] + " em " + DateTime.Now, DateTime.Now, Session["NmUsuario"].ToString());
                    
                    return RedirectToRoute("PessoaContratos", new { codcli = tbl.CD_CLIENTE, banco = dsBanco });
                //}
            }
            catch(Exception ex)
            {
                TempData["MsgErro"] = "Erro: Verificar dados, tente novamente," + ex.Message;
                
            }
            return View();
        }

        // GET: Contrato/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        public ActionResult Excluir(int id)
        {
            try
            {
                var db = Conexao.Banco;
                var hst = db.TB_CONTRATO.First(c => c.ID_CONTRATO == id);
                var ct = new Contrato(hst.CD_CONTRATO);      

                db.TB_CONTRATO.Remove(hst);
                db.SaveChanges();

                TempData["Msg"] = "Contrato excluído.";
                string dsBanco = new Contrato().RetornaNomeBanco(ct.IdBanco);
                new Historico().Exclusao(ct.CodCliente, ct.IdBanco, "Contrato " + ct.CdContrato + " excluído pelo usuário " + Session["CodUsuario"] + " em " + DateTime.Now, DateTime.Now, Session["NmUsuario"].ToString());
                return RedirectToRoute("PessoaContratos", new { codcli = ct.CodCliente, banco = dsBanco });
            }
            catch
            {
                return View();
            }
        }

        // POST: Contrato/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

sisa/Views/Contrato/Create.cshtml
@model sisa.Models.TB_CONTRATO

@{
    ViewBag.Title = "Cadastrar Contrato";
}

<h3>Cadastrar Contrato</h3>
<hr />


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="row">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="col-sm-12">
            <div class="col-sm-1">
                <label>Cod.Cliente</label>
                <input type="text" class="form-control input-sm" id="CD_CLIENTE" name="CD_CLIENTE" value="@ViewBag.CodCliente" readonly="readonly"/>
            </div>

            <div class="col-sm-1">
                <label>Cod.Banco</label>
                @Html.EditorFor(model => model.ID_BANCO, new { htmlAttributes = new { @class = "form-control input-sm", @Value = ViewBag.CodBanco, @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.ID_BANCO, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-3">
                <label>Nome do Banco</label>
                <input type="text" class="form-control input-sm" value="@ViewBag.Banco" readonly="readonly" />
            </div>
            <div class="col-sm-2">
                <label>Cod.Contrato</label>
                @Html.EditorFor(model => model.CD_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm" } })
                @Html.ValidationMessageFor(model => model.CD_CONTRATO, "", new { @class = "text-danger" })
            </div>
            <div class="col-sm-2">
                <label>Data Contrato</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-addon1"><i class="fa fa-calendar"></i></span>
                    @Html.EditorFor(model => model.DT_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm", @onkeyup = "formataData(this,event)" } })
                </div>
            </div>
            <div class="col-sm-3">
                <label>Tipo Contrato</label>
                @Html.DropDownListFor(model => model.IN_TP_CONTRATO, new SelectList(ViewBag.ListaTipoContrato, "Key", "Value", "Selecione"), new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.IN_TP_CONTRATO, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label>Informativo</label>
                @Html.DropDownListFor(model => model.AN_INFORMATIVO, new SelectList(ViewBag.ListaInformativo, "Key", "Value", "Selecione"), new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.AN_INFORMATIVO, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label>Valor Total Contrato</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-vlct">R$</span>
                    @Html.EditorFor(model => model.VL_TOT_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm"} })
                </div>
            </div>

            <div class="col-sm-2">
                <label>Data Primeiro Venc.</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-dtprimvenc"><i class="fa fa-calendar"></i></span>
                    @Html.EditorFor(model => model.DT_PRIM_VENCTO, new { htmlAttributes = new { @class = "form-control input-sm", @onkeyup = "formataData(this,event)" } })
                </div>
            </div>
            <div class="col-sm-2">
                <label>Data Ultimo Venc.</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-dtultvenc"><i class="fa fa-calendar"></i></span>
                    @Html.EditorFor(model => model.DT_ULT_VENCTO, new { htmlAttributes = new { @class = "form-control input-sm", @onkeyup = "formataData(this,event)" } })
                </div>
            </div>

            <div class="col-sm-2">
                <label>Qtd. Parcelas Pagas</label>
                @Html.EditorFor(model => model.NR_PARCELAS_PAGAS, new { htmlAttributes = new { @class = "form-control input-sm" } })
                @Html.ValidationMessageFor(model => model.NR_PARCELAS_PAGAS, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label>Valor Devido</label>
                <div class="input-group">
                    <span class="input-group-addon" id="basic-saldodev">R$</span>
                    @Html.EditorFor(model => model.VL_SALDO_DEVEDOR, new { htmlAttributes = new { @class = "form-control input-sm" } })
                </div>
            </div>
            <div class="col-sm-2">
                <label>Faixa</label>
                @Html.DropDownListFor(model => model.IN_FAIXA, new SelectList(ViewBag.ListaFaixa, "Key", "Value", "Selecione"), new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.IN_FAIXA, "", new { @class = "text-danger" })
            </div>

            <div class="col-sm-2">
                <label>Excluido</label>
                @Html.DropDownListFor(model => model.FL_EXCLUIDO, new SelectList(ViewBag.ListaExcluido, "Key", "Value", "Selecione"), new { @class = "form-control input-sm" })
                @Html.ValidationMessageFor(model => model.FL_EXCLUIDO, "", new { @class = "text-danger" })
            </div>
            
        </div>
    </div>
    <div class="row">
         <div class="col-sm-12">
            <div class="col-sm-12 margin-top">
                <input type="submit" value="Gravar" id="btnGravar" class="btn btn-success" /> |
                @Html.RouteLink("Voltar", "PessoaContratos", new {codcli = ViewBag.CodCliente, banco = ViewBag.Banco})
            </div>
         </div>
    </div>

}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        jQuery(function() {

            Calendario('DT_CONTRATO');
            Calendario('DT_PRIM_VENCTO');
            Calendario('DT_ULT_VENCTO');

            DataObrigatoria('DT_CONTRATO', 'btnGravar');
            DataObrigatoria('DT_PRIM_VENCTO', 'btnGravar');
            DataObrigatoria('DT_ULT_VENCTO', 'btnGravar');
            
            $("#VL_TOT_CONTRATO").maskMoney({ prefix: '', allowNegative: true, thousands: '', decimal: ',', affixesStay: false });
            $("#VL_SALDO_DEVEDOR").maskMoney({ prefix: '', allowNegative: true, thousands: '', decimal: ',', affixesStay: false });

            $("#btnGravar").click(function () {

                //$("#mostra").show();
                if (ValidarCampo('Cod. Contrato obrigatório...', 'CD_CONTRATO', '') &&
                   ValidarCampo('Selecione Tipo Contrato', 'IN_TP_CONTRATO', 'Selecione') &&
                   ValidarCampo('Selecione Informativo', 'AN_INFORMATIVO', 'Selecione') &&
                   ValidarCampo('Selecione Faixa', 'IN_FAIXA', 'Selecione')) {
                    return true;
                } else {
                    return false;
                }

                //if ($("#IN_TP_CONTRATO").val() == "Selecione") {
                //    ExibirMsg('Selecione Tipo Contrato');
                //    return false;
                //}
                //if ($("#AN_INFORMATIVO").val() == "Selecione") {
                //    ExibirMsg('Selecione Informativo');
                //    return false;
                //}
                //if ($("#IN_FAIXA").val() == "Selecione") {
                //    ExibirMsg('Selecione  Faixa');
                //    return false;
                //}
                //return true;
                
            });

           
        });
        
    </script>
}

sisa/Views/Contrato/Edit.cshtml
@model sisa.Models.TB_CONTRATO

@{
    ViewBag.Title = "Editar Contrato";
}

<h3>Editar Contrato</h3>
<hr />

<div class="row">
        <div class="col-sm-1">
            <label>Cod.Cliente</label>
            <input type="text" class="form-control input-sm" value="@ViewBag.CodCliente" readonly="readonly" />
        </div>
        <div class="col-sm-1">
            <label>Cod.Banco</label>
            <input class="form-control input-sm" value="@(ViewBag.CodBanco??string.Empty)" readonly="readonly" />
        </div>
        <div class="col-sm-3">
            <label>Nome do Banco</label>
            <input type="text" class="form-control input-sm" value="@(ViewBag.Banco??string.Empty)" readonly="readonly" />
        </div>
</div>

@using (Html.BeginForm("Edit", "Contrato", FormMethod.Post))
{
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "Erro", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ID_CONTRATO)
        @Html.HiddenFor(model => model.CD_CLIENTE)
        @Html.HiddenFor(model => model.ID_BANCO)

    <div class="row">
       
        <div class="col-sm-2">
            <label>Cod.Contrato</label>
            @Html.EditorFor(model => model.CD_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm" } })
        </div>
        <div class="col-sm-2">
            <label>Data Contrato</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1"><i class="fa fa-calendar"></i></span>
                @Html.EditorFor(model => model.DT_CONTRATO, new { Value = String.Format("{0:d}", Model.DT_CONTRATO), htmlAttributes = new { @class = "form-control input-sm", maxlength = 10 } })
                @*@Html.EditorFor(model => model.DT_CONTRATO, new { Value = String.Format("{0:dd/MM/yyyy}", Model.DT_CONTRATO.HasValue ? Model.DT_CONTRATO.Value.ToShortDateString() : string.Empty), htmlAttributes = new { @class = "form-control input-sm", onkeyup = "formataData(this,event)", maxlength = 10 } })*@
                @*@Html.EditorFor(model => model.DT_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm", @Value = String.Format("{0:d}", Model.DT_CONTRATO.HasValue ? Model.DT_CONTRATO.Value.ToShortDateString() : string.Empty), @onkeyup = "formataData(this,event)", maxlength = 10 } })*@
            </div>
            @*@Html.ValidationMessageFor(model => model.DT_CONTRATO, "Data Inválida", new { @class = "text-danger" })*@
        </div>

        <div class="col-sm-4">
            <label>Tipo Contrato</label>
            @Html.DropDownListFor(model => model.IN_TP_CONTRATO, new SelectList(ViewBag.ListaTipoContrato, "Key", "Value"), new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.IN_TP_CONTRATO, "", new { @class = "text-danger" })
        </div>

        <div class="col-sm-2">
            <label>Informativo</label>
            @Html.DropDownListFor(model => model.AN_INFORMATIVO, new SelectList(ViewBag.ListaInformativo, "Key", "Value"), new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.AN_INFORMATIVO, "", new { @class = "text-danger" })
        </div>

        <div class="col-sm-2">
            <label>Valor Total Contrato</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-vlct">R$</span>
                @Html.EditorFor(model => model.VL_TOT_CONTRATO, new { htmlAttributes = new { @class = "form-control input-sm" } })
            </div>
        </div>

        <div class="col-sm-2">
            <label>Data Primeiro Venc.</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-dtprimvenc"><i class="fa fa-calendar"></i></span>
                @Html.EditorFor(model => model.DT_PRIM_VENCTO, new { Value = String.Format("{0:d}", Model.DT_PRIM_VENCTO), htmlAttributes = new { @class = "form-control input-sm", maxlength = 10 } })
            </div>
        </div>
        <div class="col-sm-2">
            <label>Data Ultimo Venc.</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-dtultvenc"><i class="fa fa-calendar"></i></span>
                @Html.EditorFor(model => model.DT_ULT_VENCTO, new { Value = String.Format("{0:d}", Model.DT_ULT_VENCTO), htmlAttributes = new { @class = "form-control input-sm", maxlength = 10 } })
            </div>
        </div>

        <div class="col-sm-2">
            <label>Qtd. Parcelas Pagas</label>
            @Html.EditorFor(model => model.NR_PARCELAS_PAGAS, new { htmlAttributes = new { @class = "form-control input-sm" } })
            @Html.ValidationMessageFor(model => model.NR_PARCELAS_PAGAS, "", new { @class = "text-danger" })
        </div>

        <div class="col-sm-2">
            <label>Valor Devido</label>
            <div class="input-group">
                <span class="input-group-addon" id="basic-saldodev">R$</span>
                @Html.EditorFor(model => model.VL_SALDO_DEVEDOR, new { htmlAttributes = new { @class = "form-control input-sm" } })
            </div>
        </div>
        <div class="col-sm-2">
            <label>Faixa</label>
            @Html.DropDownListFor(model => model.IN_FAIXA, new SelectList(ViewBag.ListaFaixa, "Key", "Value", Model.IN_FAIXA), new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.IN_FAIXA, "", new { @class = "text-danger" })
        </div>

        <div class="col-sm-2">
            <label>Excluido</label>
            @Html.DropDownListFor(model => model.FL_EXCLUIDO, new SelectList(ViewBag.ListaExcluido, "Key", "Value", Model.FL_EXCLUIDO), new { @class = "form-control input-sm" })
            @Html.ValidationMessageFor(model => model.FL_EXCLUIDO, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="row">
            
                <div class="col-sm-12 margin-top">
                    <input type="submit" value="Gravar" id="btnGravar" class="btn btn-success" /> |
                    <a href="#" id="btn_excluir" data-bb="btn_excluir" class="btn btn-danger"><i class="fa fa-trash-o"></i>&nbsp;Excluir</a> |
                    @Html.RouteLink("Voltar", "PessoaContratos", new { codcli = ViewBag.CodCliente, banco = ViewBag.Banco })
                </div>
        </div>
 }


    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script>

           
            jQuery(function() {
            
                //VerificarData('DT_CONTRATO');
                //VerificarData('DT_PRIM_VENCTO');
                //VerificarData('DT_ULT_VENCTO');

                Calendario('DT_CONTRATO');
                Calendario('DT_PRIM_VENCTO');
                Calendario('DT_ULT_VENCTO');
                
                DataObrigatoria('DT_CONTRATO', 'btnGravar');
                DataObrigatoria('DT_PRIM_VENCTO', 'btnGravar');
                DataObrigatoria('DT_ULT_VENCTO', 'btnGravar');

                $("#VL_TOT_CONTRATO").maskMoney({ prefix: '', allowNegative: true, thousands: '', decimal: ',', affixesStay: false });
                $("#VL_SALDO_DEVEDOR").maskMoney({ prefix: '', allowNegative: true, thousands: '', decimal: ',', affixesStay: false });

                $("#btnGravar").click(function() {

                    $("#mostra").show();

                    if ($("#IN_TP_CONTRATO").val() == "Selecione") {
                        ExibirMsg('Selecione Tipo Contrato');
                        return false;
                    }
                    if ($("#AN_INFORMATIVO").val() == "Selecione") {
                        ExibirMsg('Selecione Informativo');
                        return false;
                    }
                    if ($("#IN_FAIXA").val() == "Selecione") {
                        ExibirMsg('Selecione  Faixa');
                        return false;
                    }
                    return true;
                });

                $("#btn_excluir").click(function() {

                    validarData(document.getElementById('DT_CONTRATO'));

                    bootbox.dialog({
                        message: "Deseja realmente excluir este contrato ?",
                        title: "Exclusão",
                        buttons: {
                            success: {
                                label: "Sim",
                                className: "btn-success",
                                callback: function() {

                                    $.ajax({
                                        cache: false,
                                        async: false,
                                        type: "POST",
                                        url: "@(Url.Action("Excluir", "Contrato"))",
                                        data: { "id": @Model.ID_CONTRATO },
                                        success: function(data) {

                                            var url = "@Url.RouteUrl("PessoaContratos", new {codcli = @Model.CD_CLIENTE, banco = ViewBag.Banco})";
                                            window.location.href = url;

                                        },
                                        error: function(xhr, ajaxOptions, thrownError) {
                                            alert("Erro, Não foi possível executar operação, tente novamente !!!");
                                        }
                                    });

                                }
                            },
                            danger: {
                                label: "Não excluir",
                                className: "btn-danger",
                                callback: function() {
                                    return true;
                                }
                            },
                        }
                    });
                });
            });

            function validarData(data) {
                var formatoValido = '/^d{2}/d{2}/d{4}$/';
                var valido = false;
                if (!formatoValido.test(data.value))
                    alert("A data está no formato errado. Por favor corrija.");
                else {
                    var dia = data.value.split("/")[0];
                    var mes = data.value.split("/")[1];
                    var ano = data.value.split("/")[2];
                    var MyData = new Date(ano, mes - 1, dia);
                    if ((MyData.getMonth() + 1 != mes) ||
                        (MyData.getDate() != dia) ||
                        (MyData.getFullYear() != ano))
                        alert("Valores inválidos para o dia, mês ou ano. Por favor corrija.");
                    else
                        valido = true;
                }
                if (valido == false) {
                    data.focus();
                    data.select();
                }
                return valido;
            }
        </script>
    }

sisa/Views/Contrato/_Bancos.cshtml
@model System.Data.DataTable
@{
    Layout = null;
}

@if (Model != null)
{

    <p>
        <table class="table table-bordered table-striped">
            @foreach (System.Data.DataRow itm in Model.Rows)
            {
                <tr><td data-dismiss="modal"><a href='@Url.Action("ListaContratos", "Pessoa", new { codcli = itm["CD_CLIENTE"], banco = itm["DS_BANCO"] })' onclick="naoconsultar"><i class="glyphicon glyphicon-briefcase"></i>&nbsp;@itm["DS_BANCO"]</a></td></tr>
            }
        </table>
        @*<center>
            <button type="button" class="btn btn-default" data-dismiss="modal" onclick="fechar()">Fechar</button>
        </center>*@
    </p>
}

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/jqueryui")

@section Scripts{
<script>
    $(document).ready(function () {
        
    });
    
</script>
}