sisa/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Antlr.Runtime;
using sisa.Models;
using sisa.DAO;

namespace sisa.Controllers
{
    public class PessoaController : Controller
    {
        private SisaEntities db = new SisaEntities();

        // GET: Pessoa
        public ActionResult Index(int codcli = 0,string banco=null,string contrato=null,int id_contrato=0)
        {
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;
            ViewBag.Contrato = contrato;
            ViewBag.IdContrato = id_contrato;
            ViewBag.ExibirConsulta = true;
            if (codcli > 0)
            {
                ViewBag.ExibirConsulta = false;
                ViewBag.Contratos = new Contrato().RetornaContratos(codcli,banco);
                ViewBag.Parcelas = new Parcela().ListaTb(codcli, banco, contrato);
            }
            return View();
        }

        public ActionResult ListaContratos(int codcli, string banco)
        {
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;

            var ct = new Contrato().RetornaContratos(codcli, banco);
            ViewBag.Contratos = ct;
            if(ct.Count()==1){
                foreach(var itm in ct){
                    ViewBag.Parcelas = new Parcela().ListaTb(codcli, banco, itm.CD_CONTRATO.ToString());
                }
            }

            ViewBag.ExibirConsulta = false;
            return View("Index");
        }

        public ActionResult ListaProcessos(int codcli, string banco, string contrato=null)
        {
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;
            ViewBag.Contrato = contrato;
            var lista = new Processo().Lista(codcli, banco);
            ViewBag.ExibirConsulta = false;
            return View("Processos",lista);
        }
        public ActionResult ListaParcelas(int codcli, string banco, string contrato)
        {
            var lista = new Parcela().ListaTb(codcli, banco, contrato);
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;
            ViewBag.Contrato = contrato;
            ViewBag.exibirConsulta = false;
            return View("Parcelas", lista);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult AutoCompletePessoa(string term)
        {
            var result = new List<KeyValuePair<string, string>>();
            IList<SelectListItem> List = new List<SelectListItem>();

            var lista = new DAO.Dados().RetornaDados("select CAST(REPLICATE('0', 7 - LEN(CD_CLIENTE)) + RTrim(CD_CLIENTE) as varchar(10))+' - '+NM_PESSOA AS NM_PESSOA,CD_CLIENTE from TB_PESSOA WHERE NM_PESSOA LIKE '" + term.ToLower() + "%'");

            /*var lista = (from r in db.TB_PESSOA
                         where r.NM_PESSOA.ToLower().Contains(term.ToLower())
                         select new { r.NM_PESSOA, r.CD_CLIENTE }).ToList();*/

            foreach (System.Data.DataRow item in lista.Rows)
            {
                result.Add(new KeyValuePair<string, string>(item["CD_CLIENTE"].ToString(), item["NM_PESSOA"].ToString()));
            }
            var result3 = result.Where(s => s.Value.ToLower().Contains(term.ToLower())).Select(w => w).ToList();

            return Json(result3, JsonRequestBehavior.AllowGet);
        }
        [AcceptVerbs(HttpVerbs.Post)]
        public JsonResult GetDetail(int id)
        {
            var pes = new TB_PESSOA();

            if (id == 0)
            {
                pes.CD_CLIENTE = 0;
                pes.NM_PESSOA = "NENHUM";
            }
            else
            {
                pes = db.TB_PESSOA.Where(p => p.CD_CLIENTE == id).SingleOrDefault();
            }
            ViewBag.CodCliente = id;
            return Json(pes);
        }

        // GET: Pessoa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_PESSOA tB_PESSOA = db.TB_PESSOA.Find(id);
            if (tB_PESSOA == null)
            {
                return HttpNotFound();
            }
            return View(tB_PESSOA);
        }

        // GET: Pessoa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_PESSOA,CD_CLIENTE,NM_PESSOA,IN_F_J,AN_CNPJ_CPF,AN_OCUPACAO,AN_CARGO,AN_RG,DT_EMISSAO_RG,AN_ORGAO_EMISSAO_RG,CD_UF_RG,AN_SEXO,DT_NASCIMENTO,AN_NATURALIDADE,AN_NACIONALIDADE,AN_ESTADO_CIVIL,AN_NOME_CONJUGE,AN_NOME_PAI,AN_NOME_MAE,DT_ALTERACAO,DT_INCLUSAO,CD_USUARIO_INC,CD_USUARIO_ALT")] TB_PESSOA tB_PESSOA)
        {
            if (ModelState.IsValid)
            {
                db.TB_PESSOA.Add(tB_PESSOA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tB_PESSOA);
        }

        // GET: Pessoa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_PESSOA tB_PESSOA = db.TB_PESSOA.Find(id);
            if (tB_PESSOA == null)
            {
                return HttpNotFound();
            }
            return View(tB_PESSOA);
        }

        // POST: Pessoa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_PESSOA,CD_CLIENTE,NM_PESSOA,IN_F_J,AN_CNPJ_CPF,AN_OCUPACAO,AN_CARGO,AN_RG,DT_EMISSAO_RG,AN_ORGAO_EMISSAO_RG,CD_UF_RG,AN_SEXO,DT_NASCIMENTO,AN_NATURALIDADE,AN_NACIONALIDADE,AN_ESTADO_CIVIL,AN_NOME_CONJUGE,AN_NOME_PAI,AN_NOME_MAE,DT_ALTERACAO,DT_INCLUSAO,CD_USUARIO_INC,CD_USUARIO_ALT")] TB_PESSOA tB_PESSOA)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tB_PESSOA).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tB_PESSOA);
        }

        // GET: Pessoa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_PESSOA tB_PESSOA = db.TB_PESSOA.Find(id);
            if (tB_PESSOA == null)
            {
                return HttpNotFound();
            }
            return View(tB_PESSOA);
        }

        // POST: Pessoa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_PESSOA tB_PESSOA = db.TB_PESSOA.Find(id);
            db.TB_PESSOA.Remove(tB_PESSOA);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sisa/Controllers/ProcessoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using sisa.Models;
using sisa.DAO;

namespace sisa.Controllers
{
    public class ProcessoController : Controller
    {
        private SisaEntities db = new SisaEntities();

        // GET: Processo
        public ActionResult Index()
        {
            return View(db.TB_PROCESSO.ToList());
        }

        // GET: Processo/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_PROCESSO tB_PROCESSO = db.TB_PROCESSO.Find(id);
            if (tB_PROCESSO == null)
            {
                return HttpNotFound();
            }
            return View(tB_PROCESSO);
        }

        public JsonResult GetTipoProcesso(int codcli, string banco, string tipo)
        {
            string nomeCliente = new Pessoa(codcli).Nome??"";
            string nomeBanco = banco;
            
            var clsTipo = new TipoProcesso();
            if (tipo == "Ativa")
            {
                clsTipo.Autor = nomeBanco;
                clsTipo.Reu = nomeCliente;
            }
            else
            {
                clsTipo.Autor = nomeCliente;
                clsTipo.Reu = nomeBanco;
            }
            //ViewBag.CodCliente = id;
            return Json(clsTipo);
        }

        void CarregaListas(string codcli,string codbanco)
        {
            var p = new Processo();
            ViewBag.LstTipoProcesso = p.ListaTipoProcesso();
            ViewBag.LstTipoAcao = p.ListaAcao();
            ViewBag.LstChancePerda = p.ListaChancePerda();
            ViewBag.LstComarca = p.ListaComarca();
            ViewBag.LstSituProcesso = p.ListaSituacaoProcesso();
            ViewBag.LstUF = p.ListaUF();
            ViewBag.LstAdvogados = p.ListaAdvogados();
            ViewBag.LstTribunal = p.ListaTribunal();
            ViewBag.LstContratos = p.ListaContratos(codcli,codbanco);
        }

        // GET: Processo/Create
        public ActionResult Create(int codcli, string banco)
        {
            ViewBag.CodCliente = codcli;
            ViewBag.Banco = banco;
            int idBanco = new Contrato().RetornaIdBanco(banco);
            ViewBag.CodBanco = idBanco;
            CarregaListas(codcli.ToString(), idBanco.ToString());
            return View();
        }

        // POST: Processo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TB_PROCESSO tbl)
        {
            try
            {
                ViewBag.CodCliente = tbl.CD_CLIENTE;
                int idBanco = tbl.ID_BANCO;
                ViewBag.Banco = new Contrato().RetornaNomeBanco(idBanco);
                ViewBag.CodBanco = idBanco;
                CarregaListas(tbl.CD_CLIENTE.ToString(), idBanco.ToString());

                //if (ModelState.IsValid)
                //{
                    db.TB_PROCESSO.Add(tbl);
                    db.SaveChanges();
                    TempData["Msg"] = "Gravado com sucesso.";
                    string dsBanco = new Contrato().RetornaNomeBanco(tbl.ID_BANCO);
                    return RedirectToRoute("PessoaProcesso", new { codcli = tbl.CD_CLIENTE, banco = dsBanco });
                //}
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro, verificar dados. "+ex.Message;
            }

            return View(tbl);
        }

        public ActionResult Editar(int? id)
        {
            TB_PROCESSO tblProcesso = null;
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                tblProcesso = db.TB_PROCESSO.Find(id);

                ViewBag.CodCliente = tblProcesso.CD_CLIENTE;
                int idBanco = tblProcesso.ID_BANCO;
                ViewBag.Banco = new Contrato().RetornaNomeBanco(idBanco);
                ViewBag.CodBanco = idBanco;
                CarregaListas(tblProcesso.CD_CLIENTE.ToString(), idBanco.ToString());
                
                if (tblProcesso == null)
                {
                    TempData["MsgErro"] = "Nenhum processo encontrato com esse Id";
                }
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro, verificar dados. " + ex.Message;
            }
            return View("Edit",tblProcesso);

        }

        // GET: Processo/Edit/5
        public ActionResult Edit(int? id, int codcli, int codbanco)
        {
            TB_PROCESSO tB_PROCESSO = null;
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                ViewBag.CodCliente = codcli;
                int idBanco = codbanco;
                ViewBag.Banco = new Contrato().RetornaNomeBanco(codbanco);
                ViewBag.CodBanco = codbanco;
                CarregaListas(codcli.ToString(), codbanco.ToString());

                tB_PROCESSO = db.TB_PROCESSO.Find(id);
                if (tB_PROCESSO == null)
                {
                    return HttpNotFound();
                }
            }
            catch (Exception ex)
            {
                TempData["MsgErro"] = "Erro, verificar dados. " + ex.Message;
            }
            return View(tB_PROCESSO);
            
        }

        // POST: Processo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TB_PROCESSO tblProcesso)
        {
            //if (ModelState.IsValid)
            //{
            //    db.Entry(tblProcesso).State = EntityState.Modified;
            //    db.SaveChanges();
            //    TempData["Msg"] = "Gravado com sucesso.";
            //}
            //else
            //{
            //    TempData["MsgErro"] = "Não foi possível gravar, verificar dados.";
            //}
            try
            {
                db.Entry(tblProcesso).State = EntityState.Modified;
                db.SaveChanges();
                TempData["Msg"] = "Gravado com sucesso.";
            }
            catch(Exception ex)
            {
                TempData["MsgErro"] = "Não foi possível gravar, verificar dados. "+ex.Message;
            }

            ViewBag.CodCliente = tblProcesso.CD_CLIENTE;
            int idBanco = tblProcesso.ID_BANCO;
            ViewBag.Banco = new Contrato().RetornaNomeBanco(idBanco);
            ViewBag.CodBanco = idBanco;
            CarregaListas(tblProcesso.CD_CLIENTE.ToString(), idBanco.ToString());
            return RedirectToAction("Edit", new { id = tblProcesso.ID_PROCESSO, codcli = tblProcesso.CD_CLIENTE, codbanco = tblProcesso.ID_BANCO });
        }

        public ActionResult Excluir(int id)
        {
            var db = Conexao.Banco;
            var hst = db.TB_PROCESSO.First(c => c.ID_PROCESSO == id);
            int CodCliente = hst.CD_CLIENTE;
            int IdBanco = hst.ID_BANCO;
            string dsBanco = new Contrato().RetornaNomeBanco(IdBanco);
            try
            {
                db.TB_PROCESSO.Remove(hst);
                db.SaveChanges();
                TempData["Msg"] = "Processo excluído.";
                new Historico().Exclusao(CodCliente, IdBanco, "Processo " + id.ToString() + " excluído pelo usuário " + Session["CodUsuario"] + " em " + DateTime.Now, DateTime.Now, Session["NmUsuario"].ToString());
                return RedirectToRoute("PessoaProcesso", new { codcli = CodCliente, banco = dsBanco });
            }
            catch(Exception ex)
            {
                TempData["Msg"] = "Erro ao tentar excluir, verificar dados. " + ex.Message;
            }
            return RedirectToAction("Edit", new { codcli = CodCliente, banco = dsBanco });
        }

        // GET: Processo/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TB_PROCESSO tB_PROCESSO = db.TB_PROCESSO.Find(id);
            if (tB_PROCESSO == null)
            {
                return HttpNotFound();
            }
            return View(tB_PROCESSO);
        }

        // POST: Processo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TB_PROCESSO tB_PROCESSO = db.TB_PROCESSO.Find(id);
            db.TB_PROCESSO.Remove(tB_PROCESSO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

sisa/Views/Pessoa/Processos.cshtml
@model IEnumerable<sisa.Models.VW_PROCESSO>
@{
   ViewBag.Title = "Processos";
   int codcli = ViewBag.CodCliente != null ? ViewBag.CodCliente : 0;
   var ExibirCliente = new sisa.DAO.Pessoa().Lista(codcli);
   var dados = new sisa.DAO.Pessoa().Dados(codcli);
}


@if (ExibirCliente.Count() > 0)
{
    <div class="row">
        <div class="col-lg-11">
            <h2>Processos</h2>
        </div>
    </div>

    @Html.Partial("~/Views/Pessoa/_Cliente.cshtml", ExibirCliente)
    @*<div class="row">
        <div class="col-lg-1 text-center">
            <p>
                <a href="@Url.Action("Index", "Pessoa", new { codcli = codcli, banco = ViewBag.Banco, ViewBag.Contrato })" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-repeat"></i>&nbsp;Voltar</a>
            </p>
        </div>
    </div>*@
}

@if (Model != null)
{
    
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4>Processos</h4>
            </div>
            <div class="panel-body">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th>CNJ</th>
                        <th>Processo</th>
                        <th class="text-center">Editar</th>
                        <th>Tipo Ação</th>
                        <th>Comarca</th>
                        <th>Contrato</th>
                    </tr>
                    @foreach (var itm in Model)
                    {
                        <tr>
                            <td>@itm.AN_CNJ</td>
                            <td>
                                @itm.AN_PROCESSO
                            </td>
                            <td class="text-center"><a href="@Url.Action("Edit", "Processo", new { id = itm.ID_PROCESSO, codcli = itm.CD_CLIENTE, codbanco = itm.ID_BANCO })" class="btn btn-default btn-sm"><i class="fa fa-align-center fa-pencil"></i></a></td>
                            <td>@itm.IN_TP_ACAO</td><td>@itm.NM_COMARCA</td><td>@itm.CD_CONTRATO</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
}

sisa/Views/Pessoa/_Cliente.cshtml
@model IEnumerable<sisa.Models.TB_PESSOA>
@{
    Layout = null;
    int codcli = ViewBag.CodCliente != null ? ViewBag.CodCliente : 0;
    string banco = ViewBag.Banco != null ? ViewBag.Banco : null;
    string contrato = ViewBag.Contrato != null ? ViewBag.Contrato : null;
}

@if (Model != null)
{

    var pes = Model.Single();
    var tel = new sisa.DAO.Pessoa();
    tel.ConsultaContato(pes.CD_CLIENTE); 
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="display-table">
                <div class="display-table-cell">
                    <h4>
                        <i class="glyphicon glyphicon-user"></i>&nbsp;Cliente
                        @if (ViewBag.Contrato != null)
                        {
                            <a href="@Url.Action("", "")" class="btn btn-default"><i class="fa fa-file"></i>&nbsp;@ViewBag.Contrato</a>
                        }
                        <a href="@Url.Action("Index", "Pessoa")" class="btn btn-success btn-sm"><i class="fa fa-search"></i>&nbsp;Nova Consulta</a>
                        @*<a href="@Url.Action("Index", "Pessoa")" class="btn btn-primary btn-sm"><i class="fa fa-user-plus"></i>&nbsp;Novo Cliente</a>*@
                        
                        <!-- Split button -->
                        <div class="btn-group btn-sm">
                            <button type="button" class="btn btn-primary btn-sm"><i class="fa fa-plus"></i>&nbsp;Cadastro</button>
                            <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="caret"></span>
                                <span class="sr-only">Toggle Dropdown</span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("Create", "Contrato", new {codcli,banco})" class=""><i class="fa fa-file-text-o"></i>&nbsp;Contrato</a></li>
                                <li><a href="@Url.Action("Create", "Processo", new {codcli,banco})"><i class="fa fa-clone"></i>&nbsp;Processo</a></li>
                                <li><a href="#"><i class="fa fa-list-alt"></i>&nbsp;Parcela</a></li>
                                <li><a href="#"><i class="fa fa-minus-circle"></i>&nbsp;Despesa</a></li>
                                <li><a href="#"><i class="fa fa-clock-o"></i>&nbsp;Honorário</a></li>
                                @*<li role="separator" class="divider"></li>
                                <li><a href="#">Separated link</a></li>*@
                            </ul>
                        </div>
                    </h4>
                   
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    <label>Nome Cliente</label>
                    <input type="text" id="nomecli" name="nomecli" class="form-control input-sm" placeholder="Pesquisa por nome do cliente" value="@pes.NM_PESSOA" />
                    <spam id="selecionar"></spam>
                    <input type="hidden" id="codcli" name="codcli" />
                </div>
                <div class="col-md-3">
                    <label>CPF/CNPJ</label>
                    <input type="text" id="cpfcnpj" name="cpfcnpj" class="form-control input-sm" value="@pes.AN_CNPJ_CPF"/>
                </div>
                <div class="col-md-3">
                    <label>Código Chave</label>
                    <input type="text" id="codchave" name="codchave" class="form-control input-sm" value="@pes.CD_CLIENTE"/>
                </div>
                <div class="col-md-3">
                    <label>Banco</label>
                    <input type="text" id="banco" name="banco" class="form-control input-sm" value="@ViewBag.Banco" />
                </div>
            </div>
            <div class="row">
                @*<div class="col-md-3">
                    <label>Agência</label>
                    <input type="text" id="agencia" name="agencia" class="form-control input-sm" />
                </div>*@
                <div class="col-lg-3">
                    <label>Status</label>
                    <input type="text" id="status" name="status" class="form-control input-sm" value="@ViewBag.Status" />
                </div>
                @*<div class="col-md-3">
                    <label>Carteira</label>
                    <input type="text" id="carteira" name="operador" class="form-control input-sm" value="@pes.AN_TX_CARTEIRA" />
                </div>*@
                <div class="col-md-3">
                    <label>Operador</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-user"></i></span>
                        <input type="text" id="operador" name="operador" class="form-control input-sm" value="@ViewBag.Operador" />
                    </div>
                </div>
                @*<div class="col-md-3">
                    <label>Proc.Substabelecido</label>
                    <input type="text" id="procsubs" name="procsubs" class="form-control input-sm" />
                </div>*@
                <div class="col-md-3">
                    <label>Localizador</label>
                    <input type="text" id="localizador" name="localizador" class="form-control input-sm" value="@tel.Localizador"/>
                </div>
                <div class="col-md-3">
                    <label>Campanha</label>
                    <input type="text" id="campanha" name="campanha" class="form-control input-sm" value="@pes.AN_TX_INFORMATIVO1" />
                </div>
                <div class="col-md-6">
                    <label>Informativo</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="informa"><i class="fa fa-comment-o"></i></span>
                        <input type="text" id="informativo" name="informativo" class="form-control input-sm" aria-describedby="informa" value="@pes.AN_TX_INFORMATIVO2" />
                    </div>
                </div>
                @*<div class="col-md-4">
                    <label>Cluster</label>
                    <input type="text" id="cluster" name="cluster" class="form-control input-sm" value="@pes.AN_CLUSTER_RATING" />
                </div>*@
                <div class="col-md-2">
                    <label>Telefone</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-phone"></i></span>
                        <input type="text" id="tel" name="tel" class="form-control input-sm" value="(@tel.DDD)@tel.Telefone" />
                    </div>
                </div>
                <div class="col-md-4">
                    <label>E-mail</label>
                    <div class="input-group">
                        <span class="input-group-addon" id="basic-addon1"><i class="fa fa-envelope-o"></i></span>
                        <input type="text" id="email" name="email" class="form-control input-sm" value="@tel.Email" />
                    </div>
                </div>
            </div>
            <div class="row">
           
            </div>
            @*<div class="row">
            <div class="col-md-12">
                <label>Recurso Auxiliar</label>
                <input type="text" id="recursoaux" name="recursoaux" class="form-control input-sm" value="@pes.AN_RECURSO_AUXILIAR" />
            </div>            
        </div>*@
        </div>
    </div>
    <div class="well well-sm">

        @if (codcli > 0 && banco != null && contrato != null)
        {
            <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-clock-o"></i>&nbsp;HONORÁRIOS/DESPESAS</a>
            @*<a href="@Url.Action("ListaParcelas", "Pessoa", new {codcli, banco, contrato} )" class="btn btn-default btn-sm"><i class="fa fa-file"></i>&nbsp;PARCELAS</a>*@
        }
        
        <a href="@Url.Action("ListaContratos", "Pessoa", new { codcli, banco})" class="btn btn-default btn-sm"><i class="fa fa-file-text-o"></i>&nbsp;CONTRATOS</a>
        <a href="@Url.Action("ListaProcessos", "Pessoa", new { codcli, banco, contrato})" class="btn btn-default btn-sm"><i class="fa fa-files-o"></i>&nbsp;PROCESSOS</a>
        <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-archive"></i>&nbsp;HISTÓRICO DA COBANÇA</a>
        <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-file-text-o"></i>&nbsp;OUTROS DADOS</a>
        <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-phone"></i>&nbsp;TELEF./ENDEREÇO</a>
        <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-thumbs-o-up"></i>&nbsp;ACORDOS</a>
        <a href="@Url.Action("", "")" class="btn btn-default btn-sm"><i class="fa fa-exclamation-circle"></i>&nbsp;OBSERVAÇÕES.</a>

    </div>
}